INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (3, 'Ceviche', 4000, 1);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (4, 'Ceviche Mixto', 4000, 1);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (5, 'Lomo Saltado', 4000, 1);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (6, 'Chicharrón de Pez', 4000, 1);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (7, 'Chicharrón de Pollo', 4000, 1);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (8, 'Chicharrón de Chancho', 4000, 1);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (9, 'Pollo a la Plancha', 4000, 1);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (10, 'Arroz Chaufa Pollo Carne', 4000, 1);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (11, 'Tallarín Saltado', 4000, 1);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (12, 'Tallarín Saltado', 4000, 1);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (13, 'Arroz con Marisco', 4000, 1);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (14, 'Combinado', 4000, 1);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (15, 'Lomo a lo Pobre', 4000, 1);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (16, 'test', 4000, 0);
INSERT INTO restorant.extra (id, descripcion, precio, visible) VALUES (17, 'test', 5000, 0);